fragment Post on Post {
  __typename
  id
  createdAt
  publishedAt
  updatedAt

  title
  slug

  body {
    raw

    # FIXME: is this supported by graphql-unwrap?
    # raw {
    #   references {
    #     ... on Person {
    #       __typename
    #       id
    #     }
    #   }
    # }
  }

}
