#import "./AssetFull.gql"
#import "./PersonFull.gql"

fragment Post on Post {
  __typename
  id
  createdAt
  publishedAt
  updatedAt

  title
  slug

  body {
    raw

    # Not supported by graphql-unwrap
    references {
      ... on Asset {
        ...AssetFull
      }

      ... on Person {
        ...PersonFull
      }
    }
  }

}
